---
swagger: "2.0"
info:
  version: "2016-10-12T00:34:01Z"
  title: "OpenAerialMap"
basePath: "/prod"
schemes:
- "https"
paths:
  /{proxy+}:
    x-amazon-apigateway-any-method:
      produces:
      - "application/json"
      parameters:
      - name: "proxy"
        in: "path"
        required: true
        type: "string"
      responses: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:534228481105:function:satelytics-dynamic-tiler_tiler/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        cacheNamespace: "0nlwk4"
        cacheKeyParameters:
        - "method.request.path.proxy"
        type: "aws_proxy"
        contentHandling: "CONVERT_TO_BINARY"
x-amazon-apigateway-binary-media-types:
- "*/*"
